### ISSUE TITLE
Fork the Monterail theme

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-dark#18]
It seems that the original Monterail theme has been kind of abandoned by its creator... Could you fork it and bring the improvements you did to your themes to the original theme, maybe?

**Comment by conema** [comment]
Are you speaking about  [Paenglab](https://addons.thunderbird.net/en-US/thunderbird/addon/monterail/)'s version or about [spymastermatt](https://github.com/spymastermatt/thunderbird-monterail)'s version?

**Comment by Rosmaninho** [comment]
Paenglab's.

**Comment by Rosmaninho** [comment]
By the way, do you know Zotero? The bibliographical reference management software? It's also based on Firefox and it's possible to configure its looks with css as well.

**Comment by conema** [comment]
> 
> 
> By the way, do you know Zotero? The bibliographical reference management software? It's also based on Firefox and it's possible to configure its looks with css as well.

I was looking for Zotero, it seems that there isn't a easy way to style it, it can be done by using the userChrome, but there aren't dev tools to easily found class names & etc.

> Paenglab's.

mhmh,  I dunno if it's been abandoned right now, it seems that it's updated with the last version of TB and the reviews are positive. Paenglab is a main dev in TB (for the theme part?), so I think that he's pretty busy. I'll wait and see how it go.  

However, the real problem is that, at the moment, I haven't enough time for do a decent new version of the theme. I'll leave this issue opened for a bit, maybe someone want to try to do it!

PS: I'll work on the other issues this evening

**Comment by Rosmaninho** [comment]
Ah, that's sad about Zotero. :(

I messed around a bit with userChrome and manage to theme it somewhat but I was facing those problems you mentioned of finding class names (and mainly because I have barely any idea of what I'm doing.

Could you elaborate what is required? I would create a post on their forums to see if they could provide that info so that it could be themed.

**Comment by Rosmaninho** [comment]
Would love for that. I spent my day yesterday fiddling with the userChrome.css someone shared there,and made something decent looking.
But it's hard to do better than that when I have zero knowledge and can't get class names.

**Comment by Rosmaninho** [comment]
I just got this reply in a thread I opened about this:

https://www.zotero.org/support/dev/client_coding/building_the_standalone_client

**Comment by conema** [comment]
I think that this is the important part 

> Running Zotero Plugins
**Zotero can run Firefox extensions as plugins**. You can run Firefox extensions from source code in Zotero the same way you could in Firefox. Create an extensions directory in the Zotero profile directory and create a file named after the id in the extension's install.rdf (e.g. zotplugin@example.com) containing the path to the extension source code. The extension will then be automatically installed when you start Zotero.

You should try to download a "dev toolbox" plugin in the [AMO](https://addons.mozilla.org/it/firefox/) and see if you can easily edit the css.
