### ISSUE TITLE
Testing for Linux & MacOS

### ISSUE THREAD

**Issue by conema** [conema/monterail-dark#2]
Like the title, we need someone to check if there are problem with the dark theme in linux/macos and with versions >52.0 and <60.0 of thunderbird

**Comment by r0ckarong** [comment]
I'm using it on openSUSE and the titles of inactive tabs are black on dark background so really hard to read and I find the fonts too big like someone mentioned in #5.

![tb_monterail_opensuse](https://user-images.githubusercontent.com/4920542/44572237-89d82b80-a783-11e8-95bb-90b6f38dd507.png)

Also in the Message editing dialog the menu items are also black font on dark background so very hard to read.

![tb_edit_msg](https://user-images.githubusercontent.com/4920542/44572236-89d82b80-a783-11e8-92be-a8976fbeef6c.png)

My biggest problem is with the huge padding around the message list rows. It makes the list less efficient and only shows about a dozen messages on my screen instead of 20+. Is that somehow configurable?

**Comment by r0ckarong** [comment]
Actually nevermind about the fonts. I confused this with the padding issue. I'll remove this from the original comment.

**Comment by conema** [comment]
The fix is now pushed on the repo, thanks for noticed that bug! I'm pushing this also in the add-on.

However, for eliminate the padding you should:
1. Go to `/home/[your linux user]/.thunderbird/[(literally) random letters and numbers].default/extensions`
2. Open the file "MonterailDark@conema.me.xpi" with a zip/rar tool (I'm using Ark)
3. Go to chrome/MonterailOverlay/css/
4. Open the file "root.css" with a file editor (or move the file in the desktop and remove on the archive)
5. Go to row 29 and edit "--message-list-row-height" with the padding that you want
6. Save and restart thunderbird

If you have any other problems, you know where find me :P

**Comment by r0ckarong** [comment]
Ok the property that you mentioned changes the row height of the folder view on the side, what I am looking for is the messages list in the main window. What property is that?
