### ISSUE TITLE
Alignment of Greek characters in the message list 

### ISSUE THREAD

**Issue by dimkard** [conema/monterail-dark#33]
Some Greek characters in the subject of the mail, as displayed in the message list pane, are not properly aligned. For example, letters π,Δ and Ω:
![Screenshot_20191001_140436](https://user-images.githubusercontent.com/5058312/65957003-6c7c9300-e454-11e9-9eb8-1d8a48b39915.png)

![Screenshot_20191001_140309](https://user-images.githubusercontent.com/5058312/65956933-3fc87b80-e454-11e9-9e28-5a89b7849c69.png)

Also, most Greek characters seem "bold", compared with the Latin ones. 

**Build information (please complete the following information):**
 - OS: KDE Neon (Ubuntu 18.04 based)
 - Version 60.8.0 (64-bt)

**Comment by conema** [comment]
Hi @dimkard,
This happens because the font that I'm using supports only Latin and Extended Latin characters, so I think that the Greek characters are using a fallback serif font. You can absolutely change the font with one that supports Greek. It can be done by editing the monterail-dark/chrome/MonterailOverlay/css/root.css file, 6th row. The best place to download fonts is Google Fonts, where you can select Latin+Greek encoding.

**Comment by dimkard** [comment]
Thanks for the detailed response; fonts are displayed properly now. And many thanks for your work on offering such a nice theme.

**Comment by conema** [comment]
You're welcome! It's sad that thunderbird killed full themes...
