### ISSUE TITLE
Delay in theme loading, default theme stays for a few seconds

### ISSUE THREAD

**Issue by meetdilip** [conema/monterail-dark#44]
**Describe the bug**

The theme takes about 3-4 seconds to load. I am not sure whether we can call this a bug. But I am using Ubuntu 18.04 and for a few seconds after starting, the default theme stays. After a few seconds, Monterail dark comes in. I am not complaining, but if you can fix it in some way, that would be great.

**To Reproduce (if applicable)**
1. Open Thunderbird 68.4.1 ( my version )
2. Let Thunderbird start
3. You will now see the default theme for a few seconds
4. Monterail Dark comes in

**Expected behavior**

Monterail Dark starts from the begining. 

**Screenshots**
Add screenshots to help explain your problem.
NA

**Build information (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu 18.04
 - Version [e.g. 60.1b] Thunderbird 68.4.1

**Additional context**
 NA

**Comment by conema** [comment]
Hi @meetdilip,
This is not a problem of the theme per se, but a problem of Thunderbird. In version 68.x, the developers removed the possibility to create the so called "full themes", so I transformed the old Monterail Dark "Full Theme" in an extension, the problem is that, extensions are loaded after that TB fully starts. So, sadly, this problem cannot be fixed.

**Comment by meetdilip** [comment]
I see. Thanks for explaining.

I need to say, your work is awesome :+1:
